template: staging

sync:
- url: https://github.com/rancher/charts.git
  branch: dev-v2.5-source
validate:
- url: https://github.com/rancher/charts.git
  branch: main
  dropReleaseCandidates: true
helmRepo:
  cname: charts.rancher.io